steps:
  - name: "init"
    commands: 
      - "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash"
      - ". ~/.nvm/nvm.sh"
      - "nvm install 16"
      - "ls"
      - "pwd"
      - "whoami"
      - "npm install"
      - "npm install -D @types/aws-lambda esbuild"
      - "npm run prebuild"
      - "npm run build"
      - "aws s3 cp dist/* s3://adarsh-source-code/ --recursive"
      - "npm run postbuild"