steps:
  - name: "init"
    commands: 
      - "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash"
      - ". ~/.nvm/nvm.sh"
      - "nvm install 16"
  - name: "installation"
    command: "npm install"
  - name: "install dependancies"
    command: "npm install -D @types/aws-lambda esbuild"
  - name: "build index.js file and copy it to s3"
    commands: 
      - "npm run prebuild"
      - "npm run build"
      - "npm run postbuild"
      - "aws s3 cp dist/* s3://adarsh-source-code/ --recursive"